
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FinPlanner.Core
{

using System;
    using System.Collections.Generic;
    
public partial class Journal
{

    public int JournalID { get; set; }

    public int AccountID { get; set; }

    public System.DateTime PostingDate { get; set; }

    public double Amount { get; set; }

    public string Description { get; set; }



    public virtual Account Account { get; set; }

}

}
