
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FinPlanner.Core
{

using System;
    using System.Collections.Generic;
    
public partial class vBalanceSheet
{

    public string AccountNo { get; set; }

    public string AccountName { get; set; }

    public double Amount { get; set; }

    public int Level { get; set; }

    public Nullable<System.DateTime> PostingDate { get; set; }

}

}
