//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinPlanner.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGoals
    {
        public int GoalNo { get; set; }
        public string GoalName { get; set; }
        public System.DateTime Due { get; set; }
    }
}
