//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinPlanner.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class vJournal
    {
        public System.DateTime PostingDate { get; set; }
        public string AccountNo { get; set; }
        public string AccountName { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
    }
}
